In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Project root
PROJECT_ROOT = Path.cwd().parent

# Cresci-2017 dataset
DATA_DIR = PROJECT_ROOT / "data" / "external" / "cresci2017"

genuine_path = DATA_DIR / "genuine_users.csv"
spam_path = DATA_DIR / "spam_user.csv"

print("Genuine file:", genuine_path)
print("Spam file:", spam_path)

print("\nGenuine exists:", genuine_path.exists())
print("Spam exists:", spam_path.exists())

Genuine file: c:\Users\Acer\Documents\AuthentiScore\data\external\cresci2017\genuine_users.csv
Spam file: c:\Users\Acer\Documents\AuthentiScore\data\external\cresci2017\spam_user.csv

Genuine exists: True
Spam exists: True

In [3]:
genuine_df = pd.read_csv(genuine_path)
spam_df = pd.read_csv(spam_path)

print("Genuine dataset shape:", genuine_df.shape)
print("Spam dataset shape:", spam_df.shape)

Genuine dataset shape: (3474, 42)
Spam dataset shape: (991, 41)

In [4]:
print("Genuine columns:")
print(genuine_df.columns.tolist())

print("\nSpam columns:")
print(spam_df.columns.tolist())

Genuine columns:
['id', 'name', 'screen_name', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'url', 'lang', 'time_zone', 'location', 'default_profile', 'default_profile_image', 'geo_enabled', 'profile_image_url', 'profile_banner_url', 'profile_use_background_image', 'profile_background_image_url_https', 'profile_text_color', 'profile_image_url_https', 'profile_sidebar_border_color', 'profile_background_tile', 'profile_sidebar_fill_color', 'profile_background_image_url', 'profile_background_color', 'profile_link_color', 'utc_offset', 'is_translator', 'follow_request_sent', 'protected', 'verified', 'notifications', 'description', 'contributors_enabled', 'following', 'created_at', 'timestamp', 'crawled_at', 'updated', 'test_set_1', 'test_set_2']

Spam columns:
['id', 'name', 'screen_name', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'url', 'lang', 'time_zone', 'location', 'default_profile', 'default_profile_image', 'geo_enabled', 'profile_image_url', 'profile_banner_url', 'profile_use_background_image', 'profile_background_image_url_https', 'profile_text_color', 'profile_image_url_https', 'profile_sidebar_border_color', 'profile_background_tile', 'profile_sidebar_fill_color', 'profile_background_image_url', 'profile_background_color', 'profile_link_color', 'utc_offset', 'is_translator', 'follow_request_sent', 'protected', 'verified', 'notifications', 'description', 'contributors_enabled', 'following', 'created_at', 'timestamp', 'crawled_at', 'updated', 'test_set_1']

In [5]:
genuine_df.head()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,url,lang,...,notifications,description,contributors_enabled,following,created_at,timestamp,crawled_at,updated,test_set_1,test_set_2
0,1502026416,TASUKU HAYAKAWA,0918Bask,2177,208,332,265,1,NaN,ja,...,NaN,15years ago X.Lines24,NaN,NaN,Tue Jun 11 11:20:35 +0000 2013,2013-06-11 13:20:35,2015-05-02 06:41:46,2016-03-15 15:53:47,0,0
1,2492782375,ro_or,1120Roll,2660,330,485,3972,5,NaN,ja,...,NaN,保守見習い地元大好き人間。 経済学、電工、仏教を勉強中、ちなDeではいかんのか？ (*^◯^*),NaN,NaN,Tue May 13 10:37:57 +0000 2014,2014-05-13 12:37:57,2015-05-01 17:20:27,2016-03-15 15:53:48,0,0
2,293212315,bearclaw,14KBBrown,1254,166,177,1185,0,NaN,en,...,NaN,Let me see what your best move is!,NaN,NaN,Wed May 04 23:30:37 +0000 2011,2011-05-05 01:30:37,2015-05-01 18:48:28,2016-03-15 15:53:48,0,0
3,191839658,pocahontas farida,wadespeters,202968,2248,981,60304,101,http://t.co/rGV0HIJGsu,en,...,NaN,20. menna: #farida #nyc and the 80s actually y...,NaN,NaN,Fri Sep 17 14:02:10 +0000 2010,2010-09-17 16:02:10,2015-05-01 13:55:16,2016-03-15 15:53:48,0,0
4,3020965143,Ms Kathy,191a5bd05da04dc,82,21,79,5,0,NaN,en,...,NaN,Cosmetologist,NaN,NaN,Fri Feb 06 04:10:49 +0000 2015,2015-02-06 05:10:49,2015-05-02 01:17:32,2016-03-15 15:53:48,0,0

In [6]:
spam_df.head()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,url,lang,...,verified,notifications,description,contributors_enabled,following,created_at,timestamp,crawled_at,updated,test_set_1
0,24858289,Davide Bertoli,davideb66,1299,22,40,1,0,NaN,it,...,NaN,NaN,NaN,NaN,NaN,Tue Mar 17 08:51:12 +0000 2009,2009-03-17 09:51:12,2014-04-19 14:46:19,2016-03-15 14:12:22,1
1,33212890,Elisa D'Ospina,ElisaDospina,18665,12561,3442,16358,110,http://t.co/ceK8TovxwI,it,...,NaN,NaN,Autrice del libro #unavitatuttacurve dal 9 apr...,NaN,NaN,Sun Apr 19 14:38:04 +0000 2009,2009-04-19 16:38:04,2014-05-18 23:20:58,2016-03-15 14:17:13,1
2,39773427,Donato Vincenzo,Vladimir65,22987,600,755,14,6,NaN,it,...,NaN,NaN,[Live Long and Prosper],NaN,NaN,Wed May 13 15:34:41 +0000 2009,2009-05-13 17:34:41,2014-05-13 23:21:54,2016-03-15 14:16:44,1
3,57007623,Rafiela Morales L.,RafielaMorales,7975,398,350,11,2,NaN,en,...,NaN,NaN,"Cuasi Odontologa*♥,#Bipolar, #Sarcastica & Som...",NaN,NaN,Wed Jul 15 12:55:03 +0000 2009,2009-07-15 14:55:03,2014-05-19 23:24:18,2016-03-15 14:18:54,1
4,63258466,§ h a † u r♄,FabrizioC_c,20218,413,405,162,8,http://t.co/PK5F0JDKcy,it,...,NaN,NaN,"I shall rise from my own death, to avenge hers...",NaN,NaN,Wed Aug 05 21:12:49 +0000 2009,2009-08-05 23:12:49,2014-05-11 23:22:23,2016-03-15 14:17:05,1

In [7]:
print("Genuine missing values:")
print(genuine_df.isnull().sum())

print("\nSpam missing values:")
print(spam_df.isnull().sum())

Genuine missing values:
id                                       0
name                                     1
screen_name                              0
statuses_count                           0
followers_count                          0
friends_count                            0
favourites_count                         0
listed_count                             0
url                                   2208
lang                                     0
time_zone                              999
location                              1109
default_profile                       2442
default_profile_image                 3461
geo_enabled                           1319
profile_image_url                        0
profile_banner_url                     309
profile_use_background_image           390
profile_background_image_url_https       0
profile_text_color                       0
profile_image_url_https                  0
profile_sidebar_border_color             0
profile_background_tile               2167
profile_sidebar_fill_color               0
profile_background_image_url             0
profile_background_color                 0
profile_link_color                       0
utc_offset                             999
is_translator                         3473
follow_request_sent                   3474
protected                             3396
verified                              3463
notifications                         3474
description                            379
contributors_enabled                  3474
following                             3474
created_at                               0
timestamp                                0
crawled_at                               0
updated                                  0
test_set_1                               0
test_set_2                               0
dtype: int64

Spam missing values:
id                                      0
name                                    0
screen_name                             0
statuses_count                          0
followers_count                         0
friends_count                           0
favourites_count                        0
listed_count                            0
url                                   969
lang                                    0
time_zone                              88
location                              246
default_profile                       846
default_profile_image                 990
geo_enabled                           973
profile_image_url                       0
profile_banner_url                    914
profile_use_background_image            3
profile_background_image_url_https      0
profile_text_color                      0
profile_image_url_https                 0
profile_sidebar_border_color            0
profile_background_tile               725
profile_sidebar_fill_color              0
profile_background_image_url            0
profile_background_color                0
profile_link_color                      0
utc_offset                             88
is_translator                         991
follow_request_sent                   991
protected                             991
verified                              991
notifications                         991
description                            48
contributors_enabled                  991
following                             991
created_at                              0
timestamp                               0
crawled_at                              0
updated                                 0
test_set_1                              0
dtype: int64

In [8]:
print("Genuine data types:")
print(genuine_df.dtypes)

print("\nSpam data types:")
print(spam_df.dtypes)

Genuine data types:
id                                      int64
name                                      str
screen_name                               str
statuses_count                          int64
followers_count                         int64
friends_count                           int64
favourites_count                        int64
listed_count                            int64
url                                       str
lang                                      str
time_zone                                 str
location                                  str
default_profile                       float64
default_profile_image                 float64
geo_enabled                           float64
profile_image_url                         str
profile_banner_url                        str
profile_use_background_image          float64
profile_background_image_url_https        str
profile_text_color                        str
profile_image_url_https                   str
profile_sidebar_border_color              str
profile_background_tile               float64
profile_sidebar_fill_color                str
profile_background_image_url              str
profile_background_color                  str
profile_link_color                        str
utc_offset                            float64
is_translator                         float64
follow_request_sent                   float64
protected                             float64
verified                              float64
notifications                         float64
description                               str
contributors_enabled                  float64
following                             float64
created_at                                str
timestamp                                 str
crawled_at                                str
updated                                   str
test_set_1                              int64
test_set_2                              int64
dtype: object

Spam data types:
id                                      int64
name                                      str
screen_name                               str
statuses_count                          int64
followers_count                         int64
friends_count                           int64
favourites_count                        int64
listed_count                            int64
url                                       str
lang                                      str
time_zone                                 str
location                                  str
default_profile                       float64
default_profile_image                 float64
geo_enabled                           float64
profile_image_url                         str
profile_banner_url                        str
profile_use_background_image          float64
profile_background_image_url_https        str
profile_text_color                        str
profile_image_url_https                   str
profile_sidebar_border_color              str
profile_background_tile               float64
profile_sidebar_fill_color                str
profile_background_image_url              str
profile_background_color                  str
profile_link_color                        str
utc_offset                            float64
is_translator                         float64
follow_request_sent                   float64
protected                             float64
verified                              float64
notifications                         float64
description                               str
contributors_enabled                  float64
following                             float64
created_at                                str
timestamp                                 str
crawled_at                                str
updated                                   str
test_set_1                              int64
dtype: object

In [9]:
print("Genuine duplicate rows:", genuine_df.duplicated().sum())
print("Spam duplicate rows:", spam_df.duplicated().sum())

Genuine duplicate rows: 0
Spam duplicate rows: 0

In [10]:
genuine_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,3474.0,NaN,NaN,NaN,951967526.421704,994239653.067533,678033.0,147554092.0,475167132.5,1655303139.5,3164941860.0
name,3473,3410,.,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
screen_name,3474,3474,0918Bask,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
statuses_count,3474.0,NaN,NaN,NaN,16958.220207,30696.286104,3.0,1810.25,6609.0,19467.0,399555.0
followers_count,3474.0,NaN,NaN,NaN,1393.219632,17216.664524,1.0,149.0,341.0,803.75,986837.0
friends_count,3474.0,NaN,NaN,NaN,633.242372,1600.962972,0.0,169.0,319.0,635.75,46310.0
favourites_count,3474.0,NaN,NaN,NaN,4669.620322,11527.566663,0.0,261.25,1286.0,4727.0,313954.0
listed_count,3474.0,NaN,NaN,NaN,19.496546,157.740969,0.0,0.0,2.0,8.0,6166.0
url,1266,1264,http://t.co/0c9HL6Xn9G,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lang,3474,24,en,3178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_zone,2475,105,Pacific Time (US & Canada),398,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,2365,1795,Philippines,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
default_profile,1032.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
default_profile_image,13.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
geo_enabled,2155.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_image_url,3474,3466,http://abs.twimg.com/sticky/default_profile_im...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_banner_url,3165,3165,https://pbs.twimg.com/profile_banners/15020264...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_use_background_image,3084.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_background_image_url_https,3474,1653,https://abs.twimg.com/images/themes/theme1/bg.png,1237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_text_color,3474,393,333333,2220,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_image_url_https,3474,3466,https://abs.twimg.com/sticky/default_profile_i...,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_sidebar_border_color,3474,182,C0DEED,1213,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_tile,1307.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_sidebar_fill_color,3474,372,DDEEF6,1657,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_image_url,3474,1653,http://abs.twimg.com/images/themes/theme1/bg.png,1237,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_color,3474,502,C0DEED,1343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_link_color,3474,851,0084B4,1343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
utc_offset,2475.0,NaN,NaN,NaN,-4386.545455,22486.293337,-39600.0,-25200.0,-14400.0,18000.0,46800.0
is_translator,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0
follow_request_sent,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
protected,78.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
verified,11.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
notifications,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,3095,3094,cchs,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contributors_enabled,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
following,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,3474,3474,Tue Jun 11 11:20:35 +0000 2013,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,3474,3474,2013-06-11 13:20:35,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crawled_at,3474,3273,2015-05-01 12:56:29,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
updated,3474,1054,2016-03-15 16:00:59,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test_set_1,3474.0,NaN,NaN,NaN,0.287853,0.452827,0.0,0.0,0.0,1.0,1.0
test_set_2,3474.0,NaN,NaN,NaN,0.141048,0.348121,0.0,0.0,0.0,0.0,1.0

In [11]:
spam_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,991.0,NaN,NaN,NaN,649048976.724521,481268237.702477,24858289.0,466280321.5,467121186.0,542212236.0,2525273432.0
name,991,928,Sara,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
screen_name,991,991,davideb66,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
statuses_count,991.0,NaN,NaN,NaN,1111.998991,5740.506607,5.0,83.0,138.0,414.5,106283.0
followers_count,991.0,NaN,NaN,NaN,1784.907164,3217.001658,0.0,0.0,234.0,3841.5,48787.0
friends_count,991.0,NaN,NaN,NaN,1853.76892,3111.163974,0.0,0.0,313.0,4087.5,45690.0
favourites_count,991.0,NaN,NaN,NaN,158.171544,2160.885086,0.0,0.0,0.0,0.0,50699.0
listed_count,991.0,NaN,NaN,NaN,3.954591,23.658149,0.0,0.0,0.0,4.0,656.0
url,22,22,http://t.co/ceK8TovxwI,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lang,991,2,it,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_zone,903,8,Athens,831,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,745,150,Roma,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN
default_profile,145.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
default_profile_image,1.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0
geo_enabled,18.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_image_url,991,991,http://abs.twimg.com/sticky/default_profile_im...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_banner_url,77,77,https://pbs.twimg.com/profile_banners/33212890...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_use_background_image,988.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_background_image_url_https,991,45,https://abs.twimg.com/images/themes/theme9/bg.gif,165,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_text_color,991,12,333333,456,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_image_url_https,991,991,https://abs.twimg.com/sticky/default_profile_i...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_sidebar_border_color,991,20,181A1E,164,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_tile,266.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
profile_sidebar_fill_color,991,23,DDEEF6,164,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_image_url,991,45,http://abs.twimg.com/images/themes/theme9/bg.gif,165,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_background_color,991,30,1A1B1F,164,NaN,NaN,NaN,NaN,NaN,NaN,NaN
profile_link_color,991,31,0084B4,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
utc_offset,903.0,NaN,NaN,NaN,10453.156146,2139.608649,-25200.0,10800.0,10800.0,10800.0,10800.0
is_translator,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
follow_request_sent,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
protected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
verified,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notifications,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
description,943,824,Carpe diem.,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contributors_enabled,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
following,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,991,985,Tue Jan 17 10:25:19 +0000 2012,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,991,985,2012-01-17 11:25:19,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
crawled_at,991,400,2014-06-09 23:20:04,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
updated,991,428,2016-03-15 14:20:10,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
test_set_1,991.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0